name: CI

on: 
  push:
    branches: 
      - master

jobs:      
  test:
    runs-on: ubunt
    steps:
      - name: Run Tests
        uses: actions/checkout@v4
      - name: NodeJs Environment
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm install
      - run: npm test
