name: Node.js CI

on:
  push:
    branches:      
      - dev
      - stg

  pull_request:
    branches:
      - master
      - dev
      - main

jobs:
  check-application:

    runs-on: ubuntu-latest

    steps:    
    - name: Checkout
      uses: actions/checkout@v4
    - name: Use Node.js 18
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'
    - name: Installing dependencies
      run: npm install jest -g && npm install
    - name: Running Tests
      run: npm test
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up qemu
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: netosantos122/mynodejs:latest

      
    